name: Update GitHub Trending

on:
  schedule:
    # 每天 UTC 时间 00:00 运行（北京时间上午 8:00）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  update-trending:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install axios cheerio

      - name: Update GitHub Trending data
        run: npm run update-trending

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code public/github-trending.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/github-trending.json
          git commit -m "chore: update GitHub Trending data $(date +'%Y-%m-%d')"
          git push

      - name: No changes detected
        if: steps.git-check.outputs.changed != 'true'
        run: echo "No changes in trending data"
